#!/bin/bash

### changelog
# rev c:	added capability to parse the suitable z coordinates for each file.
# rev d:	rewrite for 20180803-4 data with prefix meteotest (split in 4 files)

#script to convert all available cosmo files to inifor compliant format.
#requires for successful run:
#	- hourly cosmo-1 files
# ABOVE FILES NEED TO BE AVAILABLE IN SAME WORKING DIRECTORY AS THIS SCRIPT
######################################################################################################

FILES=.
fileforhhl=hhlsoil/meteotest_c1_ana_hhl_2018080400.nc
fileforsoil=hhlsoil/meteotest_c1_ana_soiltyp_2018080400.nc
#fileforhhlsoil=$(ls $FILES | egrep -o '[0-9]{10}' -m 1)


########################################## make hhl.nc file ##########################################
#
echo 'making hhl file now'

hhlz=$(ncdump -h $fileforhhl | grep -e "HHL(" -m 1 | cut -c 12-14)
#ncks -C -O -v z_1,HHL,y_1,x_1,grid_mapping_1 $fileforhhl hhl.nc
#ncks -C -O -v z_2,HHL,y_1,x_1,grid_mapping_1 $fileforhhl hhl.nc
ncks -C -O -v $hhlz,HHL,y_1,x_1,grid_mapping_1 $fileforhhl hhl.nc #made generic

#ncks -C -A -v z_bnds_1 cosmo-1_sust_2018080318.nc hhl.nc
ncrename -O -d x_1,rlon -v x_1,rlon hhl.nc
ncrename -O -d y_1,rlat -v y_1,rlat hhl.nc
ncrename -O -v grid_mapping_1,rotated_pole hhl.nc
ncrename -O -d $hhlz,height -v $hhlz,height hhl.nc #made generic

ncatted -O -a grid_mapping,HHL,o,c,'rotated_pole' hhl.nc

echo '-------- making hhl file done'



########################################## make soil.nc file ##########################################

echo 'making soil file now'
ncks -C -O -v x_1,y_1,grid_mapping_1,SOILTYP $fileforsoil soil.nc
ncrename -O -d x_1,rlon -v x_1,rlon soil.nc
ncrename -O -d y_1,rlat -v y_1,rlat soil.nc
ncrename -O -v grid_mapping_1,rotated_pole soil.nc
ncatted -O -a grid_mapping,SOILTYP,o,c,'rotated_pole' soil.nc

echo '-------- making soil file done'


########################################## make *-flow.nc and *-soil.nc files ##########################################

momentlist=$(ls $FILES | egrep -o '[0-9]{10}' | sort -t_ -u -k1,3) #lists all files from FILES directory, greps the 10 digit number seq, sorts and drops duplicates


for moment in $momentlist
do
	echo 'looking at the instant' $moment
	echo '-------- make' $moment'-flow.nc file'
	
	echo 'fetch vertical coordinates used by U,V,W,T'
	uz=$(ncdump -h meteotest_c1_ana_flow_$moment.nc | grep -e "U(" -m 1 | cut -c 16-18)
	wz=$(ncdump -h meteotest_c1_ana_flow_$moment.nc | grep -e "W(" -m 1 | cut -c 16-18)
	tsoz=$(ncdump -h meteotest_c1_ana_soil_$moment.nc | grep -e "T_SO(" -m 1 | cut -c 19-21)
	wsoz=$(ncdump -h meteotest_c1_ana_soil_$moment.nc | grep -e "W_SO(" -m 1 | cut -c 19-21)
	atmbnds=$(ncdump -h meteotest_c1_ana_flow_$moment.nc | grep -e "$uz:bounds" | cut -c 17-24)
	soilbnds=$(ncdump -h meteotest_c1_ana_soil_$moment.nc | grep -e "$wsoz:bounds" | cut -c 17-24)

	#ncks -C -O -v z_1,z_4,P,QV,y_1,x_1,grid_mapping_1,T,time,U,V,W,z_bnds_1 laf$moment.nc seg$moment-flow.nc
	ncks -C -O -v $uz,$wz,P,QV,y_1,x_1,y_2,x_2,y_3,x_3,grid_mapping_1,T,time,U,V,W,$atmbnds meteotest_c1_ana_flow_$moment.nc seg$moment-flow.nc #generalized
	echo '1 done'
	ncrename -O -d x_1,rlon -v x_1,rlon seg$moment-flow.nc
	ncrename -O -d x_2,rlon_2 -v x_2,rlon_2 seg$moment-flow.nc
	ncrename -O -d x_3,rlon_3 -v x_3,rlon_3 seg$moment-flow.nc
	echo '2 done'
    ncrename -O -d y_1,rlat -v y_1,rlat seg$moment-flow.nc
	ncrename -O -d y_2,rlat_2 -v y_2,rlat_2 seg$moment-flow.nc
	ncrename -O -d y_3,rlat_3 -v y_3,rlat_3 seg$moment-flow.nc
	echo '3 done'
	ncrename -O -d $wz,height -v $wz,height seg$moment-flow.nc
	echo '4 done'
	ncrename -O -d $uz,height_2 -v $uz,height_2 seg$moment-flow.nc
	echo '5 done'
	ncrename -O -v $atmbnds,height_2_bnds seg$moment-flow.nc
	echo '6 done'
	
	ncrename -O -v grid_mapping_1,rotated_pole seg$moment-flow.nc
	echo '---------------- make flow file done'


	echo '-------- make' $moment'-soil.nc file...'
	#ncks -O -C -v z_5,z_6,z_bnds_6,x_1,y_1,grid_mapping_1,T_SO,time,W_SO laf${moment}.nc seg$moment-soil.nc
	ncks -O -C -v $tsoz,$wsoz,$soilbnds,x_1,y_1,grid_mapping_1,T_SO,time,W_SO meteotest_c1_ana_soil_${moment}.nc seg$moment-soil.nc

	ncrename -O -d x_1,rlon -v x_1,rlon seg$moment-soil.nc
	ncrename -O -d y_1,rlat -v y_1,rlat seg$moment-soil.nc
	ncrename -O -v grid_mapping_1,rotated_pole seg$moment-soil.nc
	ncrename -O -d $tsoz,depth -v $tsoz,depth seg$moment-soil.nc
	ncrename -O -d $wsoz,depth_2 -v $wsoz,depth_2 seg$moment-soil.nc
	ncrename -O -v $soilbnds,depth_2_bnds seg$moment-soil.nc
	
	echo '---------------- make soil file done'

	echo '-------- convert depth variables to meter from millimeter'
	ncap2 -O -s 'depth=depth/1000' seg$moment-soil.nc seg$moment-soil.nc
	ncatted -O -a units,depth,o,c,'m' seg$moment-soil.nc
	ncap2 -O -s 'depth_2[depth_2]={0.005,0.02,0.06,0.18,0.54,1.62,4.86,14.58}' seg$moment-soil.nc seg$moment-soil.nc
	ncatted -O -a units,depth_2,o,c,'m' seg$moment-soil.nc
	echo '---------------- convert depth variables to meter from millimeter done'

	echo '-------- change grid_mapping attribute to rotated_pole'
	ncatted -O -a grid_mapping,W_SO,o,c,'rotated_pole' seg$moment-soil.nc
	ncatted -O -a grid_mapping,T_SO,o,c,'rotated_pole' seg$moment-soil.nc
	ncatted -O -a grid_mapping,P,o,c,'rotated_pole' seg$moment-flow.nc
	ncatted -O -a grid_mapping,QV,o,c,'rotated_pole' seg$moment-flow.nc
	ncatted -O -a grid_mapping,T,o,c,'rotated_pole' seg$moment-flow.nc
	ncatted -O -a grid_mapping,U,o,c,'rotated_pole' seg$moment-flow.nc
	ncatted -O -a grid_mapping,V,o,c,'rotated_pole' seg$moment-flow.nc
	ncatted -O -a grid_mapping,W,o,c,'rotated_pole' seg$moment-flow.nc
	
	ncatted -O -a bounds,height_2,o,c,'height_2_bnds' seg$moment-flow.nc

	echo '---------------- change grid_mapping attribute to rotated_pole done'

done






















